# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a1fc891f4e0755590ffb574cc93bfece3da47dc9b2e654e5ab87a46b6e80c80b40c82d6ecadcf48130b43ff9ee21ac71988655616790775390cb4bd4a4f66a49

test:
  secret_key_base: 7fe3d9271eb6f9609548c32dea9df0265d96d8ecbd60f6c834cda27a2fc4da592e9c30635406dc2fd1e200ba7d44991bf91f9ec30d264d6e45aa56d2fe1dbcbb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
